export const CityWeatherMock = {
  message: 'accurate',
  cod: '200',
  count: 15,
  list: [
    {
      id: 3453732,
      name: 'Pinheiros',
      coord: { lat: -23.53, lon: -46.62 },
      main: {
        temp: 12.58,
        feels_like: 10.94,
        temp_min: 12,
        temp_max: 13,
        pressure: 1018,
        humidity: 87,
      },
      dt: 1604297512,
      wind: { speed: 2.6, deg: 130 },
      sys: { country: 'BR' },
      rain: null,
      snow: null,
      clouds: { all: 40 },
      weather: [
        {
          id: 802,
          main: 'Clouds',
          description: 'scattered clouds',
          icon: '03n',
        },
      ],
    },
    {
      id: 3458611,
      name: 'Liberdade',
      coord: { lat: -23.55, lon: -46.63 },
      main: {
        temp: 12.57,
        feels_like: 10.92,
        temp_min: 12,
        temp_max: 13,
        pressure: 1018,
        humidity: 87,
      },
      dt: 1604297513,
      wind: { speed: 2.6, deg: 130 },
      sys: { country: 'BR' },
      rain: null,
      snow: null,
      clouds: { all: 40 },
      weather: [
        {
          id: 802,
          main: 'Clouds',
          description: 'scattered clouds',
          icon: '03n',
        },
      ],
    },
    {
      id: 3448439,
      name: 'Sao Paulo',
      coord: { lat: -23.55, lon: -46.64 },
      main: {
        temp: 12.56,
        feels_like: 10.91,
        temp_min: 12,
        temp_max: 13,
        pressure: 1018,
        humidity: 87,
      },
      dt: 1604297031,
      wind: { speed: 2.6, deg: 130 },
      sys: { country: 'BR' },
      rain: null,
      snow: null,
      clouds: { all: 40 },
      weather: [
        {
          id: 802,
          main: 'Clouds',
          description: 'scattered clouds',
          icon: '03n',
        },
      ],
    },
    {
      id: 3461570,
      name: 'Ibirapuera',
      coord: { lat: -23.6, lon: -46.63 },
      main: {
        temp: 12.55,
        feels_like: 10.9,
        temp_min: 12,
        temp_max: 13,
        pressure: 1018,
        humidity: 87,
      },
      dt: 1604297514,
      wind: { speed: 2.6, deg: 130 },
      sys: { country: 'BR' },
      rain: null,
      snow: null,
      clouds: { all: 40 },
      weather: [
        {
          id: 802,
          main: 'Clouds',
          description: 'scattered clouds',
          icon: '03n',
        },
      ],
    },
    {
      id: 7521912,
      name: 'Consolação',
      coord: { lat: -23.55, lon: -46.66 },
      main: {
        temp: 12.56,
        feels_like: 10.91,
        temp_min: 12,
        temp_max: 13,
        pressure: 1018,
        humidity: 87,
      },
      dt: 1604297691,
      wind: { speed: 2.6, deg: 130 },
      sys: { country: 'BR' },
      rain: null,
      snow: null,
      clouds: { all: 40 },
      weather: [
        {
          id: 802,
          main: 'Clouds',
          description: 'scattered clouds',
          icon: '03n',
        },
      ],
    },
    {
      id: 3449324,
      name: 'Sao Caetano do Sul',
      coord: { lat: -23.62, lon: -46.55 },
      main: {
        temp: 12.57,
        feels_like: 10.92,
        temp_min: 12,
        temp_max: 13,
        pressure: 1018,
        humidity: 87,
      },
      dt: 1604297031,
      wind: { speed: 2.6, deg: 130 },
      sys: { country: 'BR' },
      rain: null,
      snow: null,
      clouds: { all: 40 },
      weather: [
        {
          id: 802,
          main: 'Clouds',
          description: 'scattered clouds',
          icon: '03n',
        },
      ],
    },
    {
      id: 3458825,
      name: 'Lapa',
      coord: { lat: -23.53, lon: -46.7 },
      main: {
        temp: 12.57,
        feels_like: 10.92,
        temp_min: 12,
        temp_max: 13,
        pressure: 1018,
        humidity: 87,
      },
      dt: 1604297513,
      wind: { speed: 2.6, deg: 130 },
      sys: { country: 'BR' },
      rain: null,
      snow: null,
      clouds: { all: 40 },
      weather: [
        {
          id: 802,
          main: 'Clouds',
          description: 'scattered clouds',
          icon: '03n',
        },
      ],
    },
    {
      id: 3467431,
      name: 'Cantareira',
      coord: { lat: -23.47, lon: -46.63 },
      main: {
        temp: 12.6,
        feels_like: 10.96,
        temp_min: 12,
        temp_max: 13,
        pressure: 1017,
        humidity: 87,
      },
      dt: 1604297515,
      wind: { speed: 2.6, deg: 100 },
      sys: { country: 'BR' },
      rain: null,
      snow: null,
      clouds: { all: 75 },
      weather: [
        { id: 803, main: 'Clouds', description: 'broken clouds', icon: '04n' },
      ],
    },
    {
      id: 3456225,
      name: 'Freguesia do O',
      coord: { lat: -23.5, lon: -46.7 },
      main: {
        temp: 12.58,
        feels_like: 10.94,
        temp_min: 12,
        temp_max: 13,
        pressure: 1018,
        humidity: 87,
      },
      dt: 1604297512,
      wind: { speed: 2.6, deg: 130 },
      sys: { country: 'BR' },
      rain: null,
      snow: null,
      clouds: { all: 40 },
      weather: [
        {
          id: 802,
          main: 'Clouds',
          description: 'scattered clouds',
          icon: '03n',
        },
      ],
    },
    {
      id: 3445067,
      name: 'Vila Gopoúva',
      coord: { lat: -23.47, lon: -46.53 },
      main: {
        temp: 12.64,
        feels_like: 11.01,
        temp_min: 12,
        temp_max: 13,
        pressure: 1017,
        humidity: 87,
      },
      dt: 1604297510,
      wind: { speed: 2.6, deg: 100 },
      sys: { country: 'BR' },
      rain: null,
      snow: null,
      clouds: { all: 75 },
      weather: [
        { id: 803, main: 'Clouds', description: 'broken clouds', icon: '04n' },
      ],
    },
    {
      id: 3461786,
      name: 'Guarulhos',
      coord: { lat: -23.46, lon: -46.53 },
      main: {
        temp: 12.65,
        feels_like: 11.02,
        temp_min: 12,
        temp_max: 13,
        pressure: 1017,
        humidity: 87,
      },
      dt: 1604297032,
      wind: { speed: 2.6, deg: 100 },
      sys: { country: 'BR' },
      rain: null,
      snow: null,
      clouds: { all: 75 },
      weather: [
        { id: 803, main: 'Clouds', description: 'broken clouds', icon: '04n' },
      ],
    },
    {
      id: 3449701,
      name: 'Santo Andre',
      coord: { lat: -23.66, lon: -46.54 },
      main: {
        temp: 12.58,
        feels_like: 10.94,
        temp_min: 12,
        temp_max: 13,
        pressure: 1018,
        humidity: 87,
      },
      dt: 1604297031,
      wind: { speed: 2.6, deg: 130 },
      sys: { country: 'BR' },
      rain: null,
      snow: null,
      clouds: { all: 40 },
      weather: [
        {
          id: 802,
          main: 'Clouds',
          description: 'scattered clouds',
          icon: '03n',
        },
      ],
    },
    {
      id: 3464739,
      name: 'Diadema',
      coord: { lat: -23.69, lon: -46.62 },
      main: {
        temp: 12.56,
        feels_like: 10.91,
        temp_min: 12,
        temp_max: 13,
        pressure: 1018,
        humidity: 87,
      },
      dt: 1604297033,
      wind: { speed: 2.6, deg: 130 },
      sys: { country: 'BR' },
      rain: null,
      snow: null,
      clouds: { all: 40 },
      weather: [
        {
          id: 802,
          main: 'Clouds',
          description: 'scattered clouds',
          icon: '03n',
        },
      ],
    },
    {
      id: 3449344,
      name: 'Sao Bernardo do Campo',
      coord: { lat: -23.69, lon: -46.56 },
      main: {
        temp: 12.57,
        feels_like: 10.92,
        temp_min: 12,
        temp_max: 13,
        pressure: 1018,
        humidity: 87,
      },
      dt: 1604297031,
      wind: { speed: 2.6, deg: 130 },
      sys: { country: 'BR' },
      rain: null,
      snow: null,
      clouds: { all: 40 },
      weather: [
        {
          id: 802,
          main: 'Clouds',
          description: 'scattered clouds',
          icon: '03n',
        },
      ],
    },
    {
      id: 3457381,
      name: 'Mauá',
      coord: { lat: -23.67, lon: -46.46 },
      main: {
        temp: 12.59,
        feels_like: 10.95,
        temp_min: 12,
        temp_max: 13,
        pressure: 1018,
        humidity: 87,
      },
      dt: 1604297032,
      wind: { speed: 2.6, deg: 130 },
      sys: { country: 'BR' },
      rain: null,
      snow: null,
      clouds: { all: 40 },
      weather: [
        {
          id: 802,
          main: 'Clouds',
          description: 'scattered clouds',
          icon: '03n',
        },
      ],
    },
  ],
}
